import { chromium } from "playwright";
const [, , url, clickText, outPath] = process.argv;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("console", (msg) => { if (msg.type() === "error") errors.push(msg.text()); });
page.on("pageerror", (err) => errors.push(String(err)));
await page.goto(url, { waitUntil: "networkidle", timeout: 30000 });
await page.getByText(/admin user|dr\. ramesh|anjali sharma/i).first().click();
await page.waitForTimeout(300);
await page.screenshot({ path: outPath.replace('.png', '-menu.png') });
await page.getByText(clickText, { exact: false }).first().click({ timeout: 5000 }).catch(e => errors.push("CLICK_FAILED: " + e.message));
await page.waitForTimeout(500);
await page.screenshot({ path: outPath, fullPage: true });
console.log("URL after click:", page.url());
console.log("ERRORS:");
errors.forEach(e => console.log(" -", e));
await browser.close();
