import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("console", (msg) => { if (msg.type() === "error") errors.push(msg.text()); });
page.on("pageerror", (err) => errors.push(String(err)));
await page.goto("http://localhost:3000/tutor/profile", { waitUntil: "networkidle" });
await page.getByRole("button", { name: "Request change" }).first().click();
await page.waitForTimeout(300);
await page.screenshot({ path: process.argv[2] });
await page.getByLabel("What should it be changed to?").fill("Please correct spelling to Ramesh Chander.");
await page.getByRole("button", { name: "Send request" }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: process.argv[3] });
console.log("ERRORS:");
errors.forEach(e => console.log(" -", e));
await browser.close();
